version: "3.1"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example # ルートユーザパスワード
      MARIADB_DATABASE: yuricollectiondb # データベース名
      MARIADB_USER: develop # ユーザ名
      MARIADB_PASSWORD: develop # パスワード
      TZ: Asia/Tokyo
    ports:
      - 3306:3306 # コンテナ外部からアクセスできるようにする


  # app:
  #   build: .
  #   container_name: springboot-app
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/mydb
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: password
  #   depends_on:
  #     - db
